-- Force RLS on all tables (ensures even table owners are subject to RLS)
ALTER TABLE public.affiliate_user_access FORCE ROW LEVEL SECURITY;
ALTER TABLE public.affiliates FORCE ROW LEVEL SECURITY;
ALTER TABLE public.app_store_reviews FORCE ROW LEVEL SECURITY;
ALTER TABLE public.appsflyer_campaigns FORCE ROW LEVEL SECURITY;
ALTER TABLE public.appsflyer_events FORCE ROW LEVEL SECURITY;
ALTER TABLE public.attributed_users FORCE ROW LEVEL SECURITY;
ALTER TABLE public.auto_response_settings FORCE ROW LEVEL SECURITY;
ALTER TABLE public.channel_weights FORCE ROW LEVEL SECURITY;
ALTER TABLE public.daily_ad_spend FORCE ROW LEVEL SECURITY;
ALTER TABLE public.daily_affiliate_spend FORCE ROW LEVEL SECURITY;
ALTER TABLE public.daily_appsflyer_clicks FORCE ROW LEVEL SECURITY;
ALTER TABLE public.daily_appsflyer_installs FORCE ROW LEVEL SECURITY;
ALTER TABLE public.dashboard_configs FORCE ROW LEVEL SECURITY;
ALTER TABLE public.google_play_reviews FORCE ROW LEVEL SECURITY;
ALTER TABLE public.mixpanel_events FORCE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_metrics FORCE ROW LEVEL SECURITY;
ALTER TABLE public.pending_responses FORCE ROW LEVEL SECURITY;
ALTER TABLE public.profiles FORCE ROW LEVEL SECURITY;
ALTER TABLE public.range_metrics_cache FORCE ROW LEVEL SECURITY;
ALTER TABLE public.report_definitions FORCE ROW LEVEL SECURITY;
ALTER TABLE public.review_settings FORCE ROW LEVEL SECURITY;
ALTER TABLE public.sync_function_logs FORCE ROW LEVEL SECURITY;
ALTER TABLE public.trustpilot_reviews FORCE ROW LEVEL SECURITY;
ALTER TABLE public.typeform_surveys FORCE ROW LEVEL SECURITY;
ALTER TABLE public.user_identity_map FORCE ROW LEVEL SECURITY;
ALTER TABLE public.user_invitations FORCE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles FORCE ROW LEVEL SECURITY;
ALTER TABLE public.weekly_metrics FORCE ROW LEVEL SECURITY;

-- Revoke all public/anon access from all tables
REVOKE ALL ON public.affiliate_user_access FROM anon, public;
REVOKE ALL ON public.affiliates FROM anon, public;
REVOKE ALL ON public.app_store_reviews FROM anon, public;
REVOKE ALL ON public.appsflyer_campaigns FROM anon, public;
REVOKE ALL ON public.appsflyer_events FROM anon, public;
REVOKE ALL ON public.attributed_users FROM anon, public;
REVOKE ALL ON public.auto_response_settings FROM anon, public;
REVOKE ALL ON public.channel_weights FROM anon, public;
REVOKE ALL ON public.daily_ad_spend FROM anon, public;
REVOKE ALL ON public.daily_affiliate_spend FROM anon, public;
REVOKE ALL ON public.daily_appsflyer_clicks FROM anon, public;
REVOKE ALL ON public.daily_appsflyer_installs FROM anon, public;
REVOKE ALL ON public.dashboard_configs FROM anon, public;
REVOKE ALL ON public.google_play_reviews FROM anon, public;
REVOKE ALL ON public.mixpanel_events FROM anon, public;
REVOKE ALL ON public.monthly_metrics FROM anon, public;
REVOKE ALL ON public.pending_responses FROM anon, public;
REVOKE ALL ON public.profiles FROM anon, public;
REVOKE ALL ON public.range_metrics_cache FROM anon, public;
REVOKE ALL ON public.report_definitions FROM anon, public;
REVOKE ALL ON public.review_settings FROM anon, public;
REVOKE ALL ON public.sync_function_logs FROM anon, public;
REVOKE ALL ON public.trustpilot_reviews FROM anon, public;
REVOKE ALL ON public.typeform_surveys FROM anon, public;
REVOKE ALL ON public.user_identity_map FROM anon, public;
REVOKE ALL ON public.user_invitations FROM anon, public;
REVOKE ALL ON public.user_roles FROM anon, public;
REVOKE ALL ON public.weekly_metrics FROM anon, public;

-- Grant SELECT to authenticated role on tables that need it (RLS policies still apply)
GRANT SELECT ON public.affiliate_user_access TO authenticated;
GRANT SELECT ON public.affiliates TO authenticated;
GRANT SELECT ON public.app_store_reviews TO authenticated;
GRANT SELECT ON public.appsflyer_campaigns TO authenticated;
GRANT SELECT ON public.appsflyer_events TO authenticated;
GRANT SELECT ON public.attributed_users TO authenticated;
GRANT SELECT ON public.auto_response_settings TO authenticated;
GRANT SELECT ON public.channel_weights TO authenticated;
GRANT SELECT ON public.daily_ad_spend TO authenticated;
GRANT SELECT ON public.daily_affiliate_spend TO authenticated;
GRANT SELECT ON public.daily_appsflyer_clicks TO authenticated;
GRANT SELECT ON public.daily_appsflyer_installs TO authenticated;
GRANT SELECT ON public.dashboard_configs TO authenticated;
GRANT SELECT ON public.google_play_reviews TO authenticated;
GRANT SELECT ON public.mixpanel_events TO authenticated;
GRANT SELECT ON public.monthly_metrics TO authenticated;
GRANT SELECT ON public.pending_responses TO authenticated;
GRANT SELECT ON public.profiles TO authenticated;
GRANT SELECT ON public.range_metrics_cache TO authenticated;
GRANT SELECT ON public.report_definitions TO authenticated;
GRANT SELECT ON public.review_settings TO authenticated;
GRANT SELECT ON public.sync_function_logs TO authenticated;
GRANT SELECT ON public.trustpilot_reviews TO authenticated;
GRANT SELECT ON public.typeform_surveys TO authenticated;
GRANT SELECT ON public.user_identity_map TO authenticated;
GRANT SELECT ON public.user_invitations TO authenticated;
GRANT SELECT ON public.user_roles TO authenticated;
GRANT SELECT ON public.weekly_metrics TO authenticated;